# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Polite Hedonist
subtitle: Kurt Gardiner
email: k.a.gardiner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes from books I've read, thoughts I've had, ramblings of my
  other interests around IT, culture, and the general human
  condition. Posts sporadically.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://krutisfood.github.com" # the base hostname & protocol for your site
twitter_username: krutisfood
github_username:  krutisfood

# Build settings
markdown:          kramdown
theme: jekyll-theme-clean-blog
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
