# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: krut
title: The Polite Hedonist
email: k.a.gardiner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place to jot notes from books I've read.  It may expand to
  ramblings of my other interests around IT, culture and general human
  condition.  Let's embark on the journey of a thousand steps!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://krutisfood.github.com" # the base hostname & protocol for your site
twitter_username: krutisfood
github_username:  krutisfood 

# Build settings
markdown: kramdown
